import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import PageTransition from "../components/PageTransition";
import StairTransition from "../components/StairTransition";


const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <StairTransition />
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
    </ClerkProvider>
  )
}
